name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore StylishFSharpSolutions/StylishFSharpSolutions.sln
    - name: Build
      run: dotnet build StylishFSharpSolutions/StylishFSharpSolutions.sln --no-restore
    - name: Test
      run: dotnet test StylishFSharpSolutions/StylishFSharpSolutions.sln --no-build --verbosity normal
